In [1]:
import pandas as pd

In [4]:
df_cts = pd.read_csv('/Users/elyselee/Documents/HackCville/City_time_series.csv')
df_cts.head()

,Date,RegionName,InventorySeasonallyAdjusted_AllHomes,InventoryRaw_AllHomes,MedianListingPricePerSqft_1Bedroom,MedianListingPricePerSqft_2Bedroom,MedianListingPricePerSqft_3Bedroom,MedianListingPricePerSqft_4Bedroom,MedianListingPricePerSqft_5BedroomOrMore,MedianListingPricePerSqft_AllHomes,...,ZHVI_BottomTier,ZHVI_CondoCoop,ZHVI_MiddleTier,ZHVI_SingleFamilyResidence,ZHVI_TopTier,ZRI_AllHomes,ZRI_AllHomesPlusMultifamily,ZriPerSqft_AllHomes,Zri_MultiFamilyResidenceRental,Zri_SingleFamilyResidenceRental
0,1996-04-30,abbottstownadamspa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,108700.0,NaN,NaN,NaN,NaN,NaN
1,1996-04-30,aberdeenbinghamid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,168400.0,NaN,NaN,NaN,NaN,NaN
2,1996-04-30,aberdeenharfordmd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,81300.0,137900.0,109600.0,108600.0,147900.0,NaN,NaN,NaN,NaN,NaN
3,1996-04-30,aberdeenmonroems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,74500.0,NaN,NaN,NaN,NaN,NaN
4,1996-04-30,aberdeenmoorenc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,131100.0,NaN,NaN,NaN,NaN,NaN

In [5]:
import plotly
plotly.tools.set_credentials_file(username='enl', api_key='oABDQTz6KKUvwYasHqKq')

In [6]:
df_cts['year'] = pd.DatetimeIndex(df_cts['Date']).year
df_cts.head()

,Date,RegionName,InventorySeasonallyAdjusted_AllHomes,InventoryRaw_AllHomes,MedianListingPricePerSqft_1Bedroom,MedianListingPricePerSqft_2Bedroom,MedianListingPricePerSqft_3Bedroom,MedianListingPricePerSqft_4Bedroom,MedianListingPricePerSqft_5BedroomOrMore,MedianListingPricePerSqft_AllHomes,...,ZHVI_CondoCoop,ZHVI_MiddleTier,ZHVI_SingleFamilyResidence,ZHVI_TopTier,ZRI_AllHomes,ZRI_AllHomesPlusMultifamily,ZriPerSqft_AllHomes,Zri_MultiFamilyResidenceRental,Zri_SingleFamilyResidenceRental,year
0,1996-04-30,abbottstownadamspa,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,108700.0,NaN,NaN,NaN,NaN,NaN,1996
1,1996-04-30,aberdeenbinghamid,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,168400.0,NaN,NaN,NaN,NaN,NaN,1996
2,1996-04-30,aberdeenharfordmd,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,137900.0,109600.0,108600.0,147900.0,NaN,NaN,NaN,NaN,NaN,1996
3,1996-04-30,aberdeenmonroems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,74500.0,NaN,NaN,NaN,NaN,NaN,1996
4,1996-04-30,aberdeenmoorenc,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,131100.0,NaN,NaN,NaN,NaN,NaN,1996

In [7]:
df_groupby_datebr=df_cts.groupby(df_cts['year'])[['ZHVI_1bedroom','ZHVI_2bedroom','ZHVI_3bedroom','ZHVI_4bedroom', 'ZHVI_5BedroomOrMore']].mean()

In [8]:
#Bar Chart
#Mean house values by Bedrooms type and year
import plotly.graph_objs as go
import plotly.plotly as py
trace1 = go.Bar(
                x = df_groupby_datebr.index.values,
                y = df_groupby_datebr.ZHVI_1bedroom,
                name = "ZHVI_1bedroom",
                marker = dict(color = 'rgb(102,255,255)'),
                text = df_groupby_datebr['ZHVI_1bedroom'])
trace2 = go.Bar(
                x = df_groupby_datebr.index.values,
                y = df_groupby_datebr.ZHVI_2bedroom,
                name = "ZHVI_2bedroom",
                marker = dict(color = 'rgb(102,178,255)'),
                text = df_groupby_datebr['ZHVI_2bedroom'])
trace3 = go.Bar(
                x = df_groupby_datebr.index.values,
                y = df_groupby_datebr.ZHVI_3bedroom.values,
                name = "ZHVI_3bedroom",
                marker = dict(color = 'rgb(102,102,255)'),
                text = df_groupby_datebr['ZHVI_3bedroom'])
trace4 = go.Bar(
                x = df_groupby_datebr.index.values,
                y = df_groupby_datebr.ZHVI_4bedroom.values,
                name = "ZHVI_4bedroom",
                marker = dict(color = 'rgb(178, 102, 255)'),
                text = df_groupby_datebr['ZHVI_4bedroom'])
trace5 = go.Bar(
                x = df_groupby_datebr.index.values,
                y = df_groupby_datebr.ZHVI_5BedroomOrMore.values,
                name = "ZHVI_5BedroomOrMore",
                marker = dict(color = 'rgb(255, 102, 255)'),
                text = df_groupby_datebr['ZHVI_5BedroomOrMore'])
data = [trace1, trace2, trace3, trace4, trace5]
layout = go.Layout(barmode = "group", title="Bar Chart: Mean House Values by Bedrooms and Year",
                   xaxis= dict(title= 'Year',ticklen= 5,zeroline= False), 
                   yaxis= dict(title= 'Mean House Values',ticklen= 5,zeroline= False))
fig = go.Figure(data = data, layout = layout)
url = py.plot(fig, validate=False)

In [ ]:
#Line Chart
#Mean house values by bedrooms and year
trace1 = go.Scatter(
                x = df_groupby_datebr.index.values,
                y = df_groupby_datebr.ZHVI_1bedroom,
                mode = "lines+markers",
                name = "ZHVI_1bedroom",
                marker = dict(color = 'rgb(102,255,255)'),
                text = df_groupby_datebr['ZHVI_1bedroom'])
trace2 = go.Scatter(
                x = df_groupby_datebr.index.values,
                y = df_groupby_datebr.ZHVI_2bedroom,
                mode = "lines+markers",
                name = "ZHVI_2bedroom",
                marker = dict(color = 'rgb(102,178,255)'),
                text = df_groupby_datebr['ZHVI_2bedroom'])
trace3 = go.Scatter(
                x = df_groupby_datebr.index.values,
                y = df_groupby_datebr.ZHVI_3bedroom.values,
                mode = "lines+markers",
                name = "ZHVI_3bedroom",
                marker = dict(color = 'rgb(102,102,255)'),
                text = df_groupby_datebr['ZHVI_3bedroom'])
trace4 = go.Scatter(
                x = df_groupby_datebr.index.values,
                y = df_groupby_datebr.ZHVI_4bedroom.values,
                mode = "lines+markers",
                name = "ZHVI_4bedroom",
                marker = dict(color = 'rgb(178, 102, 255)'),
                text = df_groupby_datebr['ZHVI_4bedroom'])
trace5 = go.Scatter(
                x = df_groupby_datebr.index.values,
                y = df_groupby_datebr.ZHVI_5BedroomOrMore.values,
                mode = "lines+markers",
                name = "ZHVI_5BedroomOrMore",
                marker = dict(color = 'rgb(255, 102, 255)'),
                text = df_groupby_datebr['ZHVI_5BedroomOrMore'])
data = [trace1, trace2, trace3, trace4, trace5]
layout = go.Layout(title = 'Line Plot: Mean House Values by Bedrooms and Year',
              xaxis= dict(title= 'Year',ticklen= 5,zeroline= False),
              yaxis= dict(title= 'Mean House Values',ticklen= 5,zeroline= False)
             )
fig = go.Figure(data = data, layout = layout)
url = py.plot(fig, validate=False)

In [9]:
df_sts = pd.read_csv('/Users/elyselee/Documents/HackCville/State_time_series.csv')
df_sts.columns

Index(['Date', 'RegionName', 'DaysOnZillow_AllHomes',
       'InventorySeasonallyAdjusted_AllHomes', 'InventoryRaw_AllHomes',
       'MedianListingPricePerSqft_1Bedroom',
       'MedianListingPricePerSqft_2Bedroom',
       'MedianListingPricePerSqft_3Bedroom',
       'MedianListingPricePerSqft_4Bedroom',
       'MedianListingPricePerSqft_5BedroomOrMore',
       'MedianListingPricePerSqft_AllHomes',
       'MedianListingPricePerSqft_CondoCoop',
       'MedianListingPricePerSqft_DuplexTriplex',
       'MedianListingPricePerSqft_SingleFamilyResidence',
       'MedianListingPrice_1Bedroom', 'MedianListingPrice_2Bedroom',
       'MedianListingPrice_3Bedroom', 'MedianListingPrice_4Bedroom',
       'MedianListingPrice_5BedroomOrMore', 'MedianListingPrice_AllHomes',
       'MedianListingPrice_CondoCoop', 'MedianListingPrice_DuplexTriplex',
       'MedianListingPrice_SingleFamilyResidence',
       'MedianPctOfPriceReduction_AllHomes',
       'MedianPctOfPriceReduction_CondoCoop',
       'MedianPctOfPriceReduction_SingleFamilyResidence',
       'MedianPriceCutDollar_AllHomes', 'MedianPriceCutDollar_CondoCoop',
       'MedianPriceCutDollar_SingleFamilyResidence',
       'MedianRentalPricePerSqft_1Bedroom',
       'MedianRentalPricePerSqft_2Bedroom',
       'MedianRentalPricePerSqft_3Bedroom',
       'MedianRentalPricePerSqft_4Bedroom',
       'MedianRentalPricePerSqft_5BedroomOrMore',
       'MedianRentalPricePerSqft_AllHomes',
       'MedianRentalPricePerSqft_CondoCoop',
       'MedianRentalPricePerSqft_DuplexTriplex',
       'MedianRentalPricePerSqft_MultiFamilyResidence5PlusUnits',
       'MedianRentalPricePerSqft_SingleFamilyResidence',
       'MedianRentalPricePerSqft_Studio', 'MedianRentalPrice_1Bedroom',
       'MedianRentalPrice_2Bedroom', 'MedianRentalPrice_3Bedroom',
       'MedianRentalPrice_4Bedroom', 'MedianRentalPrice_5BedroomOrMore',
       'MedianRentalPrice_AllHomes', 'MedianRentalPrice_CondoCoop',
       'MedianRentalPrice_DuplexTriplex',
       'MedianRentalPrice_MultiFamilyResidence5PlusUnits',
       'MedianRentalPrice_SingleFamilyResidence', 'MedianRentalPrice_Studio',
       'ZHVIPerSqft_AllHomes', 'PctOfHomesDecreasingInValues_AllHomes',
       'PctOfHomesIncreasingInValues_AllHomes',
       'PctOfHomesSellingForGain_AllHomes',
       'PctOfHomesSellingForLoss_AllHomes',
       'PctOfListingsWithPriceReductionsSeasAdj_AllHomes',
       'PctOfListingsWithPriceReductionsSeasAdj_CondoCoop',
       'PctOfListingsWithPriceReductionsSeasAdj_SingleFamilyResidence',
       'PctOfListingsWithPriceReductions_AllHomes',
       'PctOfListingsWithPriceReductions_CondoCoop',
       'PctOfListingsWithPriceReductions_SingleFamilyResidence',
       'PriceToRentRatio_AllHomes', 'Sale_Counts', 'Sale_Counts_Seas_Adj',
       'Sale_Prices', 'ZHVI_1bedroom', 'ZHVI_2bedroom', 'ZHVI_3bedroom',
       'ZHVI_4bedroom', 'ZHVI_5BedroomOrMore', 'ZHVI_AllHomes',
       'ZHVI_BottomTier', 'ZHVI_CondoCoop', 'ZHVI_MiddleTier',
       'ZHVI_SingleFamilyResidence', 'ZHVI_TopTier', 'ZRI_AllHomes',
       'ZRI_AllHomesPlusMultifamily', 'ZriPerSqft_AllHomes',
       'Zri_MultiFamilyResidenceRental', 'Zri_SingleFamilyResidenceRental'],
      dtype='object')

In [ ]:
#Multiple Scatter Plots
from plotly import tools
trace1 = go.Scatter(x=df_sts.MedianListingPrice_1Bedroom,
    y=df_sts.MedianListingPrice_2Bedroom, mode='markers',
    name = "1Bedroom&2Bedroom", marker = dict(
          color = 'rgb(102,255,255)'))
trace2 = go.Scatter(x=df_sts.MedianListingPrice_2Bedroom,
    y=df_sts.MedianListingPrice_3Bedroom, mode='markers',
    name = "2Bedroom&3Bedroom", marker = dict(
          color = 'rgb(102,178,255)'))
trace3 = go.Scatter( x=df_sts.MedianListingPrice_3Bedroom,
    y=df_sts.MedianListingPrice_4Bedroom, mode='markers',
    name = "3Bedroom&4Bedroom", marker = dict(
          color = 'rgb(102,102,255)'))
trace4 = go.Scatter(x=df_sts.MedianListingPrice_4Bedroom,
    y=df_sts.MedianListingPrice_5BedroomOrMore, mode='markers',
    name = "4Bedroom&5+Bedroom", marker = dict(
          color = 'rgb(178, 102, 255)'))

fig = tools.make_subplots(rows=2, cols=2, subplot_titles=("1Bedroom & 2Bedroom", "2Bedroom & 3Bedroom",
                                                          "3Bedroom&4Bedroom", "4Bedroom&5+Bedroom"))

fig.append_trace(trace1, 1, 1)
fig.append_trace(trace2, 1, 2)
fig.append_trace(trace3, 2, 1)
fig.append_trace(trace4, 2, 2)

fig['layout']['xaxis3'].update(title='Median Listing Price')#showgrid=False
fig['layout']['xaxis4'].update(title='Median Listing Price')

fig['layout']['yaxis1'].update(title='Median Listing Price')
fig['layout']['yaxis3'].update(title='Median Listing Price')

fig['layout'].update(height=600, width=600, title='Mutiple Scatter Plots: Median Listing Price of' +
                                                  ' Bedrooms')
url = py.plot(fig, validate=False)

In [ ]:
#Time Series Line Chart
state_list = df_state.groupby('RegionName')[['ZHVI_BottomTier']].mean().sort_values(
            by='ZHVI_BottomTier', ascending=False)[:5].index.values.tolist()
colors = dict(zip(state_list, sns.color_palette("GnBu_d", len(state_list)).as_hex()))


trace_list = []
for state in state_list:
    trace = go.Scatter(
        y=df_state[df_state['RegionName']==state]['ZHVI_BottomTier'].tolist(),
        x=df_state[df_state['RegionName']==state]['Date'].tolist(),
        mode='lines',
        name=state,
        line = dict(
                    color = colors[state],
                    width = 1.5,
#                    dash = 'dot'
                    )
        )
    trace_list.append(trace)
    
    
layout = go.Layout(
    xaxis=dict(title='Year from 1996 to 2017', zeroline=False, rangeslider=dict(visible=True)),
    yaxis=dict(title='ZHVI BottomTier', zeroline=False),

    title='Zillow Home Value Index for Top 5 States',
    showlegend=True,
    )



fig = go.Figure(data=trace_list, layout=layout)
url = py.plot(fig, validate=False, filename='ZHVI BottomTier')

In [ ]:
#Choropleth 
price_state_year = df_state.groupby(['RegionName','year'])[['MedianListingPricePerSqft_AllHomes']].mean()
#price_state.swaplevel('year','RegionName')
#price_state_year['Year'] = price_state_year.index.get_level_values(level=1)
#price_state_year['State'] = price_state_year.index.get_level_values(level=0)
price_state_year.reset_index(inplace=True)
price_state_year


#price_state_year.groupby(level='RegionName').mean()
#price_state_2017 = price_state_year.xs(2017, level=1, drop_level=False)
#%%
trace_list = []
for state in sorted(price_state_year.RegionName.unique().tolist(),reverse=True):
    trace = go.Box(
        x=price_state_year.MedianListingPricePerSqft_AllHomes[price_state_year.RegionName==state],
#        boxpoints='all',
#        jitter=0.3,
        name=state,
        marker=dict(color='rgb(178, 102, 255)')
        )
    trace_list.append(trace)
data = trace_list
layout = go.Layout(
    xaxis=dict(title='Median Listing Price Per Sqft for All Homes', zeroline=False),
    boxmode='group',
    boxgap=0.0,
    showlegend=False
)
fig = go.Figure(data=data, layout=layout)
py.plot(fig, validate=False, filename='Median Listing Price Per Sqft')